name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eed1a2b88fb7f6c0e2218431918c2b58d7deb53e3c5d2eb72005e2f4f806493a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
