name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cabaf4d952752a5eb4b0afdb5e1757fad27af34c1b7b6f5773c56abaea8d0035"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
