name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94e9e87e30762f18894d725de7ec6ea2c2ff3826eeccac54a5a4b551807c0671"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
