name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d66d927b35baf4ce9248054d28a9c7599aebb2e41e53842676cba2681beeb5c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
