name = "Fabric"
author = "Petingoso"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce17373fa9ae009b1cb7423f9238cde62d3e73aae870e484edab07e3dbecff7d"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
