name = "Fabric"
author = "Petingoso"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9467632b49fdbdd841e9d03af5e2b31aa87bca83c84ec6fe7394b8f3949d4399"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
