name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6d4ce9f3cffda3cf517e8dac332d40731567201db6a45ea11ec2042d2df659b"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
