name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "012e8d676153898d3eba84219db07e08497213ef21df2cb5fcd6cdb46f60cf1f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
