name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c23b5d3f6a7e0610e27490f58971a088d607cd725000bdb9a6c293c39c81a04b"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
