name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "839caf897fa09b67d2c5b827d47fcbbfecda0d7e69e2bc826ea5496d8be8eb1a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
