name = "Fabric"
author = "Petingoso"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "480976f60603d807f1accc89c906d268092f51d8969e845e2e907e0226ec8ca5"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
