name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d9130c20964ae253760ee51e57028e5f0a3a42ea6de0333cda5b766579bb557"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
