name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbd973d88f36a60d16660de6b92776817905877f7f96121288b5a3cc4a1f51d9"

[versions]
fabric = "0.16.0"
minecraft = "1.21.1"
