name = "Fabric"
author = "Petingoso"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "700d0d6f17b09766982322f92778dbcbf920c4b22dde38d504c4e319b6a5ba3f"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
