name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4d4a2e2b86496cee9a23371cf968f880c03214ae41bbec8bfdd0a30650f9660"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
