name = "Fabric"
author = "Petingoso"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c55588051b89a9189a2941fe67c4b907c9e3da766cf91d3f1b2605486ed7da07"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
