name = "Fabric"
author = "Petingoso"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aef6811283b904a87dee4abf02599ad83695114dc4c762b6a1675cd1560f484"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
