name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbcdb5c2107e03b01134768bb5b991c63b6473b50ec0f30efd8d3c072c704a1a"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
