name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d65b4eb67a319af77f1e59f29c161f5a28b49b4614338ade976d326b9c4fb10e"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
