name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "316f37721e7453fcfd4aa93f35988650154fcc26f326e21ffaa2e5a099e6e735"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
