name = "Fabric"
author = "Petingoso"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "972bdd66ed3ba164d573aff67bf8d1ac784b2cbe9d147260a128da5fbc23e8d1"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
