name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a438161431406d56518b53932171b71bdd3d7211855eef23fca2bd44ced4ae"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
