name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0fccc4a11ba5aecc3f40110514880945c927b6be8c79ab5fb9c102e04ccbefd"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
