name = "Fabric"
author = "Petingoso"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c16bc7dfba15b9367b36ae4bbf3d820f505ca57a7a6c3a7edfa04e0c277a237a"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
