name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c813d4f868a6aad8d48bbd4a4fd5a628ee5fbcea6c9a013e758d8fed37264480"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
